// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/verilog.proto

package verilog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerilogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionID  uint32                 `protobuf:"varint,1,opt,name=submissionID,proto3" json:"submissionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerilogRequest) Reset() {
	*x = VerilogRequest{}
	mi := &file_proto_verilog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerilogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerilogRequest) ProtoMessage() {}

func (x *VerilogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_verilog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerilogRequest.ProtoReflect.Descriptor instead.
func (*VerilogRequest) Descriptor() ([]byte, []int) {
	return file_proto_verilog_proto_rawDescGZIP(), []int{0}
}

func (x *VerilogRequest) GetSubmissionID() uint32 {
	if x != nil {
		return x.SubmissionID
	}
	return 0
}

type VerilogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerilogResponse) Reset() {
	*x = VerilogResponse{}
	mi := &file_proto_verilog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerilogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerilogResponse) ProtoMessage() {}

func (x *VerilogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_verilog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerilogResponse.ProtoReflect.Descriptor instead.
func (*VerilogResponse) Descriptor() ([]byte, []int) {
	return file_proto_verilog_proto_rawDescGZIP(), []int{1}
}

func (x *VerilogResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_verilog_proto protoreflect.FileDescriptor

var file_proto_verilog_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x6c, 0x6f, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0e,
	0x56, 0x65, 0x72, 0x69, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x22, 0x23, 0x0a, 0x0f, 0x56, 0x65, 0x72, 0x69, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x43, 0x0a, 0x0b, 0x53, 0x6f, 0x6d, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x6c, 0x6f, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_verilog_proto_rawDescOnce sync.Once
	file_proto_verilog_proto_rawDescData []byte
)

func file_proto_verilog_proto_rawDescGZIP() []byte {
	file_proto_verilog_proto_rawDescOnce.Do(func() {
		file_proto_verilog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_verilog_proto_rawDesc), len(file_proto_verilog_proto_rawDesc)))
	})
	return file_proto_verilog_proto_rawDescData
}

var file_proto_verilog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_verilog_proto_goTypes = []any{
	(*VerilogRequest)(nil),  // 0: proto.VerilogRequest
	(*VerilogResponse)(nil), // 1: proto.VerilogResponse
}
var file_proto_verilog_proto_depIdxs = []int32{
	0, // 0: proto.SomeService.Run:input_type -> proto.VerilogRequest
	1, // 1: proto.SomeService.Run:output_type -> proto.VerilogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_verilog_proto_init() }
func file_proto_verilog_proto_init() {
	if File_proto_verilog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_verilog_proto_rawDesc), len(file_proto_verilog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_verilog_proto_goTypes,
		DependencyIndexes: file_proto_verilog_proto_depIdxs,
		MessageInfos:      file_proto_verilog_proto_msgTypes,
	}.Build()
	File_proto_verilog_proto = out.File
	file_proto_verilog_proto_goTypes = nil
	file_proto_verilog_proto_depIdxs = nil
}
