name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"
          cache: true
          cache-dependency-path: go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --timeout=10m

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Convert repo name to lowercase
        run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push api container
        id: docker_build_api
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}-api:latest
          context: .
          file: ./deployments/api.Dockerfile

      - name: Build and push verilog container
        id: docker_build_verilog
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}-verilog:latest
          context: .
          file: ./deployments/verilog.Dockerfile

      - name: Deploy api
        uses: deploys-app/deploys-action@v1
        with:
          project: our-grader
          location: gke.cluster-rcf2
          name: backend
          image: ghcr.io/${{ env.REPO_NAME }}-api@${{ steps.docker_build_api.outputs.digest }}

        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}

      - name: Deploy verilog
        uses: deploys-app/deploys-action@v1
        with:
          project: our-grader
          location: gke.cluster-rcf2
          name: verilog
          image: ghcr.io/${{ env.REPO_NAME }}-verilog@${{ steps.docker_build_verilog.outputs.digest }}

        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
